Controllers/Hotel_DataController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Hotel_Management;
using System.IO;

namespace Hotel_Management.Controllers
{
    [Authorize(Roles ="Admin")]
    public class Hotel_DataController : Controller
    {
        private HotelEntities db = new HotelEntities();

        // GET: Hotel_Data
        public ActionResult Index()
        {
            return View(db.Hotel_Data.ToList());
        }

        // GET: Hotel_Data/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hotel_Data hotel_Data = db.Hotel_Data.Find(id);
            if (hotel_Data == null)
            {
                return HttpNotFound();
            }
            return View(hotel_Data);
        }

        // GET: Hotel_Data/Create
        public ActionResult Create()
        {
            return View();
        }

        

        // POST: Hotel_Data/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( Hotel_Data hotel_Data)
        {
           
            if (ModelState.IsValid)
            {
                string file1 = Path.GetFileNameWithoutExtension(hotel_Data.ImageFile1.FileName);
                string ext = Path.GetExtension(hotel_Data.ImageFile1.FileName);
                file1 = file1 + DateTime.Now.ToString("yymmssfff") + ext;
                hotel_Data.img1 = "~/Image/" + file1;
                file1 = Path.Combine(Server.MapPath("~/Image/"), file1);
                hotel_Data.ImageFile1.SaveAs(file1);

                string file2 = Path.GetFileNameWithoutExtension(hotel_Data.ImageFile2.FileName);
                string ext2 = Path.GetExtension(hotel_Data.ImageFile2.FileName);
                file2 = file2 + DateTime.Now.ToString("yymmssfff") + ext2;
                hotel_Data.img2 = "~/Image/" + file2;
                file2 = Path.Combine(Server.MapPath("~/Image/"), file2);
                hotel_Data.ImageFile2.SaveAs(file2);

                db.Hotel_Data.Add(hotel_Data);
                db.SaveChanges();
                return RedirectToAction("Index");
                
            }

            return View(hotel_Data);
        }

        // GET: Hotel_Data/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hotel_Data hotel_Data = db.Hotel_Data.Find(id);
            if (hotel_Data == null)
            {
                return HttpNotFound();
            }
            return View(hotel_Data);
        }

        // POST: Hotel_Data/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( Hotel_Data hotel_Data)
        {
            
            if (ModelState.IsValid)
            {
                db.Entry(hotel_Data).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(hotel_Data);
        }

        // GET: Hotel_Data/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hotel_Data hotel_Data = db.Hotel_Data.Find(id);
            if (hotel_Data == null)
            {
                return HttpNotFound();
            }
            return View(hotel_Data);
        }

        // POST: Hotel_Data/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Hotel_Data hotel_Data = db.Hotel_Data.Find(id);
            db.Hotel_Data.Remove(hotel_Data);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/UserdatasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Hotel_Management;



namespace Hotel_Management.Controllers
{
    [Authorize]
    public class UserdatasController : Controller
    {
        private HotelEntities db = new HotelEntities();

        // GET: Userdatas
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View(db.Userdatas.ToList());
        }
        public ActionResult Home(string search,string cat,string name)
        {
            return View(db.Hotel_Data.Where(x => x.City.Contains(search) && x.Rating.Contains(cat) && x.Hotel_name.Contains(name)).ToList());
        }
      

        // GET: Userdatas/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Userdata userdata = db.Userdatas.Find(id);
            if (userdata == null)
            {
                return HttpNotFound();
            }
            return View(userdata);
        }
        /*
        // GET: Userdatas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Userdatas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Username,Password,Email")] Userdata userdata)
        {
            if (ModelState.IsValid)
            {
                db.Userdatas.Add(userdata);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(userdata);
        }
        */
        // GET: Userdatas/Edit/5
        /*
        [Authorize(Roles ="User")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Userdata userdata = db.Userdatas.Find(id);
            if (userdata == null)
            {
                return HttpNotFound();
            }
            return View(userdata);
        }

        // POST: Userdatas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "User")]
        public ActionResult Edit([Bind(Include = "Id,Username,Password,Email")] Userdata userdata)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userdata).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(userdata);
        }
        */
        // GET: Userdatas/Delete/5
        /*
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Userdata userdata = db.Userdatas.Find(id);
            if (userdata == null)
            {
                return HttpNotFound();
            }
            return View(userdata);
        }
        [Authorize(Roles = "Admin")]
        // POST: Userdatas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        
        public ActionResult DeleteConfirmed(int id)
        {
            Userdata userdata = db.Userdatas.Find(id);
            db.Userdatas.Remove(userdata);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        */

        [AllowAnonymous]
        public ActionResult About()
        {
            return View();

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Hotel Manage</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Hotel Management", "Home", "Userdatas", new { area = "" }, new { @class = "navbar-brand" , @style = " color : white; " })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav" style="margin-left:30%">
                    <li>@Html.ActionLink("About", "About", "Userdatas", null, new { @style = " color : #00ccff;" })</li>

                    @if (User.Identity.IsAuthenticated)
                    {
                        if (User.IsInRole("Admin"))
                        {
                            <li>@Html.ActionLink("Manage Hotel", "Index", "Hotel_Data", null, new { @style = " color : #00ccff;" })</li>
                            <li>@Html.ActionLink("Confirm Bookings", "ConfirmBooking", "RoomData", null, new { @style = " color : #00ccff;" })</li>
                        }
                    }

                    @if (User.Identity.IsAuthenticated)
                    {
                        if (Session["id"] != "2")
                        {
                        <li>@Html.ActionLink("My Bookings", "MyBookings", "RoomData", null, new { @style = " color : #00ccff;" })</li>
                        }
                        <li>@Html.ActionLink("Logout", "Logout", "Account", null, new { @style = " color : #00ccff;" })</li>
                        <li style=" color : white;margin-top:15px;">Welcome, @Session["name"]</li>
                    }

                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Hotel Management</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>